/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "test.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sensorT, sensorT, AUTO)


PB_BIND(sensorTH, sensorTH, AUTO)


PB_BIND(sensorTHM, sensorTHM, AUTO)


PB_BIND(sensorBMP, sensorBMP, AUTO)


PB_BIND(sensorBMPTH, sensorBMPTH, AUTO)


PB_BIND(sensorGas, sensorGas, AUTO)


PB_BIND(sensorGyroAccel, sensorGyroAccel, AUTO)


PB_BIND(sensorTHC, sensorTHC, AUTO)



